---
abstract: 'Schedule POE events using rfc2445 recurrences.'
author:
  - 'Loïc TROCHET <losyme@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-ICal
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DateTime: 0
  DateTime::Event::ICal: 0
  POE: 0
  POE::Component::Schedule: 0
resources:
  repository: https://github.com/losyme/POE-Component-ICal
version: 0.03
